language: php
php:
  - 5.5
  - 5.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

before_script:
  - mysql -e 'create database fribone_test;' -uroot
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - cd application/application/tests
  - chmod +x fakesendmail.sh
  - sudo mkdir -p /var/qmail/bin
  - sudo cp fakesendmail.sh /var/qmail/bin/sendmail
  - sudo cp fakesendmail.sh /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -r 'echo PHP_VERSION;'`/etc/conf.d/sendmail.ini"
  - cd ../../..
  - ls -l

script:
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage/clover.xml