language: php
php:
  - 5.5
  - 5.4

before_script:
  - mysql -e 'create database fribone_test;' -uroot

script:
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage/clover.xml